"use client";

import type { Template } from "tinacms";
import { tinaField } from "tinacms/dist/react";
import { Section } from "../layout/section";
import { sectionBlockSchemaField } from "../layout/section";
import { useLanguage } from "./hooks/useLanguage";
import { parseMultiLingualText } from "@/lib/client-utils";
import dynamic from "next/dynamic";
import { useEffect, useState } from "react";

/* ---------- types (will be generated by Tina after first build) ---------- */
// We use a loose type so the file compiles before codegen runs.
// After `tina dev` the canonical PageBlocksContactMap type can be imported.
interface ContactMapData {
    background?: string | null;
    title?: string | null;
    description?: string | null;
    address?: string | null;
    zoom?: number | null;
}

/* ---------- Nominatim geocoding (free, no API key) ---------- */
interface LatLng {
    lat: number;
    lng: number;
}

async function geocode(address: string): Promise<LatLng | null> {
    try {
        const url = `https://nominatim.openstreetmap.org/search?${new URLSearchParams({
            q: address,
            format: "json",
            limit: "1",
        })}`;
        const res = await fetch(url, {
            headers: { "User-Agent": "TrementSamples/1.0" },
        });
        const data = await res.json();
        if (data?.[0]) {
            return { lat: Number.parseFloat(data[0].lat), lng: Number.parseFloat(data[0].lon) };
        }
    } catch {
        /* fall through */
    }
    return null;
}

/* ---------- Leaflet map (client-only, loaded via next/dynamic) ---------- */
const LeafletMap = dynamic(
    () =>
        import("./contact-map-leaflet").then((mod) => mod.LeafletMap),
    { ssr: false, loading: () => <MapSkeleton /> },
);

function MapSkeleton() {
    return (
        <div className="w-full aspect-[16/9] rounded-lg bg-muted animate-pulse flex items-center justify-center">
            <span className="text-muted-foreground text-sm">Loading map…</span>
        </div>
    );
}

/* ---------- Main block component ---------- */
export const ContactMap = ({ data }: { data: ContactMapData }) => {
    const lang = useLanguage();
    const [coords, setCoords] = useState<LatLng | null>(null);
    const [loading, setLoading] = useState(true);

    const address = data.address ?? "";
    const zoom = data.zoom ?? 16;

    useEffect(() => {
        if (!address) {
            setLoading(false);
            return;
        }
        let cancelled = false;
        setLoading(true);
        geocode(address).then((result) => {
            if (!cancelled) {
                setCoords(result);
                setLoading(false);
            }
        });
        return () => {
            cancelled = true;
        };
    }, [address]);

    return (
        <Section background={data.background!}>
            <div className="mx-auto max-w-4xl space-y-8 px-6">
                {data.title && (
                    <div className="text-center space-y-2">
                        <h2
                            className="text-4xl font-medium lg:text-5xl"
                            data-tina-field={tinaField(data as any, "title")}
                        >
                            {parseMultiLingualText(data.title, lang)}
                        </h2>
                        {data.description && (
                            <p
                                className="text-muted-foreground"
                                data-tina-field={tinaField(data as any, "description")}
                            >
                                {parseMultiLingualText(data.description, lang)}
                            </p>
                        )}
                    </div>
                )}

                {/* Map */}
                {loading ? (
                    <MapSkeleton />
                ) : coords ? (
                    <LeafletMap lat={coords.lat} lng={coords.lng} zoom={zoom} address={address} />
                ) : (
                    /* Fallback when geocoding fails or no address */
                    address && (
                        <div className="w-full aspect-[16/9] rounded-lg bg-muted flex items-center justify-center">
                            <span className="text-muted-foreground text-sm">
                                Could not locate address on map
                            </span>
                        </div>
                    )
                )}

                {/* Address text */}
                {address && (
                    <p
                        className="text-center text-lg text-muted-foreground"
                        data-tina-field={tinaField(data as any, "address")}
                    >
                        📍 {address}
                    </p>
                )}
            </div>
        </Section>
    );
};

/* ---------- Tina schema ---------- */
export const contactMapBlockSchema: Template = {
    name: "contactMap",
    label: "Contact Map",
    ui: {
        previewSrc: "/blocks/content.png",
        defaultItem: {
            title: "es::Encuéntranos;;en::Find Us",
            description: "es::Ven a visitarnos;;en::Come visit us",
            address: "Calle de Verdi 42, Gràcia, Barcelona",
            zoom: 16,
        },
    },
    fields: [
        sectionBlockSchemaField as any,
        {
            type: "string",
            label: "Title",
            name: "title",
        },
        {
            type: "string",
            label: "Description",
            name: "description",
        },
        {
            type: "string",
            label: "Address",
            name: "address",
            description: "Full street address. The map will geocode this automatically.",
        },
        {
            type: "number",
            label: "Zoom Level",
            name: "zoom",
            description: "Map zoom (1 = world, 18 = building). Default: 16",
        },
    ],
};
